### ISSUE TITLE
Common css/js

### ISSUE THREAD

**Issue by ivandokov** [ivandokov/rockety#16]
Often you may need to have common css/js files which are used in multiple sources, but simply adding a folder `common` doesn't trigger build and refresh, because the folder is not part of a source.

Probably changing the config like this will do the trick
```
watch:
    reload:
          - public/**/*.html
    tasks:
        - src/common/**/*.{scss,less}: 
              - css
        - src/common/**/*.js:
              - js
```
